### ISSUE TITLE
How do you resize the button in a UIBarButtonItem?

### ISSUE THREAD

**Issue by MarkLyck** [robb/hamburger-button#10]
I'm having quite some trouble sizing the button down to a normal UIBarButtonItem size.

I added the code, from the answer to another question on this repository, about using this in a UIBarButtonItem:

hamburgerMenu = HamburgerButton(frame: CGRectMake(0, 0, 54, 54))
hamburgerMenu.addTarget(self, action: "toggle:", forControlEvents:.TouchUpInside)
let revealButtonItem = UIBarButtonItem(customView: hamburgerMenu)        
self.navigationItem.leftBarButtonItem = revealButtonItem

Naturally I Tried changing the CGRectMake width and Height. But that causes it to mess up, and it doesn't resize.

**Comment by robb** [comment]
I'd say you should go through the tutorial and build a path that suits your needs. This button was never meant to be a reusable component but rather an example how to do these things yourself, sorry!.
